services:
  tor:
    image: ghcr.io/steffsas/tor-docker:latest 
    container_name: "tor-relay"
    restart: on-failure:5
    ports:
      - "5050:5050"
    networks:
      - "tor"
    volumes:
      # signature keys
      - ./keys:/var/lib/tor/.tor/keys/
      # config file
      - ./torrc:/etc/tor/torrc
networks:
  tor:
    enable_ipv6: true
    driver: bridge